### ISSUE TITLE
contiv-compose instllation error

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/install#32] opened 2017-02-16 02:57 UTC
With latest beta2 version

```

TASK [docker : check docker-compose version] ***********************************
fatal: [node2]: FAILED! => {"changed": true, "cmd": "docker-compose --version", "delta": "0:00:00.002427", "end": "2017-02-16 02:56:07.196436", "failed": true, "rc": 127, "start": "2017-02-16 02:56:07.194009", "stderr": "/bin/sh: docker-compose: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
fatal: [node3]: FAILED! => {"changed": true, "cmd": "docker-compose --version", "delta": "0:00:00.004267", "end": "2017-02-16 02:56:07.331148", "failed": true, "rc": 127, "start": "2017-02-16 02:56:07.326881", "stderr": "/bin/sh: docker-compose: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
fatal: [node1]: FAILED! => {"changed": true, "cmd": "docker-compose --version", "delta": "0:00:00.004044", "end": "2017-02-16 02:56:07.334328", "failed": true, "rc": 127, "start": "2017-02-16 02:56:07.330284", "stderr": "/bin/sh: docker-compose: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [docker : download and install docker-compose] ****************************
changed: [node2]
changed: [node1]
changed: [node3]

TASK [docker : check contiv-compose version] ***********************************
fatal: [node2]: FAILED! => {"changed": true, "cmd": "contiv-compose --version", "delta": "0:00:00.002615", "end": "2017-02-16 02:56:15.713991", "failed": true, "rc": 127, "start": "2017-02-16 02:56:15.711376", "stderr": "/bin/sh: contiv-compose: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
fatal: [node1]: FAILED! => {"changed": true, "cmd": "contiv-compose --version", "delta": "0:00:00.003675", "end": "2017-02-16 02:56:18.832096", "failed": true, "rc": 127, "start": "2017-02-16 02:56:18.828421", "stderr": "/bin/sh: contiv-compose: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
fatal: [node3]: FAILED! => {"changed": true, "cmd": "contiv-compose --version", "delta": "0:00:00.003446", "end": "2017-02-16 02:56:18.818676", "failed": true, "rc": 127, "start": "2017-02-16 02:56:18.815230", "stderr": "/bin/sh: contiv-compose: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
```

is it expected ? If we are not using contiv-compose , we should not be installing via ansible imo.

**Comment by neelimamukiri** [comment] 2017-02-16 03:26
Version check is expected to fail when the component is not installed. It seems to be the ansible way of check if required version component is installed, and if not install it.

Please open ansible issues in contiv/ansible. I'm closing this as it is expected behavior.

**Closed by neelimamukiri** 2017-02-16 03:26 UTC
